[package]
name = "memory-model"
version = "0.1.0"
authors = ["Liu Jiang <gerry@linux.alibaba.com>"]

[features]
default = ["memory-backend-mmap"]
memory-backend-mmap = []

[dependencies]
libc = ">=0.2.39"

[dev-dependencies]
tempfile = ">=3.0.2"
